"""add email column to users

Revision ID: 7e88b1fa74bb
Revises: a9a38d50b445
Create Date: 2025-09-05 03:35:02.779284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e88b1fa74bb'
down_revision = 'a9a38d50b445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vs_registry')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('vs',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=10),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_column('email')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('vs',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)

    op.create_table('vs_registry',
    sa.Column('vs', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('vs')
    )
    # ### end Alembic commands ###
