"""Add original_product_id to SoldProduct

Revision ID: 2e4ec2dcb9f4
Revises: ec401abaf626
Create Date: 2025-07-15 23:00:21.477887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e4ec2dcb9f4'
down_revision = 'ec401abaf626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sold_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_product_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sold_product', schema=None) as batch_op:
        batch_op.drop_column('original_product_id')

    # ### end Alembic commands ###
